apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: game
  labels:
    app: vishnuops-game
spec:
  type: ClusterIP
  selector:
    app: vishnuops-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

